name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ml-pipeline-cloud
          install_components: 'gke-gcloud-auth-plugin'

      - name: Build Docker image
        run: |
          docker build -t europe-west1-docker.pkg.dev/ml-pipeline-cloud/ml-repo/mlpipeline .

      - name: Push Docker image
        run: |
          docker push europe-west1-docker.pkg.dev/ml-pipeline-cloud/ml-repo/mlpipeline

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ml-pipelineservice \
            --image=europe-west1-docker.pkg.dev/ml-pipeline-cloud/ml-repo/mlpipeline \
            --region=europe-west1 \
            --platform=managed \
            --allow-unauthenticated


